#! /bin/sh

if [ ! -f "$TERRAFORM_PROVIDER_BINARY" ]; then
  echo "Provider binary not found. Please provide the path to the binary using the TERRAFORM_PROVIDER_BINARY environment variable" >&2
  exit 1
fi

while [ $# != 0 ]; do
  if [ "$1" = "-o" ]; then
    dir="$(dirname "$2")"

    mkdir -p "$dir"
    cp "$TERRAFORM_PROVIDER_BINARY" "$2"
    exit $?
  fi

  shift
done

echo "Output path not provided" >&2

exit 2
